### ISSUE TITLE
No cars found in account

### ISSUE THREAD

**Issue by stijnpieters** [leeyuentuen/polestar_api#104]
As the title suggests, I'm getting a "No cars found in account" error.
When login in on the page mentioned in the repo, I don't seem to have a "cars" tab either.

However, after just wildly guessing, the following endpoint did show me my car and its correct VIN: https://polestarid.eu.polestar.com/Account/cars

Any possibility the VIN enumeration could be done through this?

```
This error originated from a custom integration.

Logger: custom_components.polestar_api.config_flow
Source: custom_components/polestar_api/config_flow.py:43
Integration: Polestar API (documentation)
First occurred: 20:52:21 (2 occurrences)
Last logged: 20:55:06

Unexpected error creating device
Traceback (most recent call last):
  File "/config/custom_components/polestar_api/config_flow.py", line 43, in _create_device
    await device.init()
  File "/config/custom_components/polestar_api/polestar.py", line 35, in init
    await self.polestarApi.init()
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 40, in init
    await self._get_vehicle_data()
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 115, in _get_vehicle_data
    raise PolestarNoDataException("No cars found in account")
custom_components.polestar_api.pypolestar.exception.PolestarNoDataException: No cars found in account
```

**Comment by leeyuentuen** [comment]
same issue here:

https://github.com/leeyuentuen/polestar_api/issues/90

you should be not the owner with that account. maybe check other account or contact polestar to transfer that to you account.
