### ISSUE TITLE
After updating to 1.2.2 - Error while setting up polestar_api platform for sensor

### ISSUE THREAD

**Issue by Stroell** [leeyuentuen/polestar_api#33]
Hi, 
after updating from 1.2.0 to 1.2.2 it stopped working with the following error:

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:361
Integration: Sensor (documentation, issues)
First occurred: 9:23:00 PM (1 occurrences)
Last logged: 9:23:00 PM

Error while setting up polestar_api platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/polestar_api/sensor.py", line 392, in async_setup_entry
    sensors = [
              ^
  File "/config/custom_components/polestar_api/sensor.py", line 393, in <listcomp>
    PolestarSensor(device, description) for description in POLESTAR_SENSOR_TYPES
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/polestar_api/sensor.py", line 416, in __init__
    self.translation_key = f"polestar_{description.key}"
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: property 'translation_key' of 'PolestarSensor' object has no setter

![image](https://github.com/leeyuentuen/polestar_api/assets/42348774/8b737fe5-bdd4-4d8f-9301-8fa5255c1d5e)

**Comment by Stroell** [comment]
Fixed in 1.2.3
