### ISSUE TITLE
Error setting up platform in latest 1.2.4

### ISSUE THREAD

**Issue by fredrike** [leeyuentuen/polestar_api#34]
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:361
Integration: Sensor (documentation, issues)
First occurred: December 26, 2023 at 17:52:36 (2 occurrences)
Last logged: 08:20:39

Error while setting up polestar_api platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/polestar_api/sensor.py", line 392, in async_setup_entry
    sensors = [
              ^
  File "/config/custom_components/polestar_api/sensor.py", line 393, in <listcomp>
    PolestarSensor(device, description) for description in POLESTAR_SENSOR_TYPES
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/polestar_api/sensor.py", line 416, in __init__
    self.translation_key = f"polestar_{description.key}"
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: property 'translation_key' of 'PolestarSensor' object has no setter

**Comment by leeyuentuen** [comment]
still exist in latest beta version 1.2.3?

**Comment by fredrike** [comment]
I did a re-download and now it works thank you for the nice work!
