### ISSUE TITLE
No cars found in account

### ISSUE THREAD

**Issue by developerjam** [leeyuentuen/polestar_api#50]
Installed the plugin in Home Assistant. Restarted and logged in with my app credentials.

I am getting this error:

> 2023-12-29 19:47:48.453 ERROR (MainThread) [custom_components.polestar_api.pypolestar.polestar] No cars found in account
NoneType: None
2023-12-29 19:47:48.454 ERROR (MainThread) [custom_components.polestar_api.config_flow] Unexpected error creating device
Traceback (most recent call last):
  File "/config/custom_components/polestar_api/config_flow.py", line 45, in _create_device
    await device.init()
  File "/config/custom_components/polestar_api/polestar.py", line 30, in init
    await self.polestarApi.init()
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 29, in init
    await self._get_vehicle_data()
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 100, in _get_vehicle_data
    raise PolestarNoDataException("No cars found in account")
custom_components.polestar_api.pypolestar.exception.PolestarNoDataException: No cars found in account

I am located in Denmark, if regional URLs, APIs or accounts might influence this?

**Comment by loebse** [comment]
Can you see your polestar when you log in to your account in polestar.com? I guess not, so your car is not registered with your account.

**Comment by developerjam** [comment]
I cannot find it when I log in through the website. I can see the order when I bought the car, but the actual car is not there.

I get an error when I type in the VIN and associate it on the webpage (new owner cannot be the same as current owner). Guess I need to contact Polestar to fix this.

My credentials work just fine in the app, which I am using as car key.

Apparently not an issue in this code, but an issue at Polestar. Thanks anyways. :)
